# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado-projects/pipeline_cpu/pipeline_cpu.cache/wt [current_project]
set_property parent.project_path E:/Vivado-projects/pipeline_cpu/pipeline_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files e:/Vivado-projects/pipeline_cpu/mips_31_mars_board_switch.coe
add_files e:/Vivado-projects/pipeline_cpu/mips_31_mars_simulate.coe
add_files e:/Vivado-projects/pipeline_cpu/mips_54_mars_board_switch_student.coe
add_files -quiet e:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/ROM/ROM.dcp
set_property used_in_implementation false [get_files e:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/ROM/ROM.dcp]
read_verilog -library xil_defaultlib {
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/MULU.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/MUL.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/RegFile.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/MEM_WB_Reg.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/LOHI.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/IF_Module.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/IF_ID_Reg.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/ID_EX_Reg.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/EX_MEM_Reg.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Data_CONF.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Control.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Compartor.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Assist_ALU.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/ALU.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Pipeline_Core.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Data_Mem.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/sw_mem_sel.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/seg7x16.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/io_sel.v
  E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/Pipeline_cpu.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/constrs_1/new/pipeline_xdc.xdc
set_property used_in_implementation false [get_files E:/Vivado-projects/pipeline_cpu/pipeline_cpu.srcs/constrs_1/new/pipeline_xdc.xdc]


synth_design -top Pipeline_cpu -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Pipeline_cpu.dcp

catch { report_utilization -file Pipeline_cpu_utilization_synth.rpt -pb Pipeline_cpu_utilization_synth.pb }
